
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 🏕️KoA Personalization
* Environment: Production
* Id: f189fcee-05bc-0069-1f34-a1d35d692446
* 
* -------------------------------------------------------------------------------
**/

/**
 * Type representing all languages
 */
export type LanguageCodenames = "de-DE" | "default" | "English_-_Students" | "English_Students" | "es-ES";

/**
 * Type representing all content types
 */
export type ContentTypeCodenames =
  | "a_b_cta"
  | "article"
  | "blog_post"
  | "bynder_image"
  | "call_to_action"
  | "campground"
  | "disclaimer"
  | "event"
  | "form__hubspot_integration"
  | "landing_page"
  | "page"
  | "person"
  | "product"
  | "reusable_content_block"
  | "service"
  | "video";

/**
 * Type representing all collections
 */
export type CollectionCodenames =
  | "alpine"
  | "austin_east"
  | "bar_harbor"
  | "campground_template"
  | "default"
  | "lake_conroe"
  | "operations"
  | "orlando"
  | "portland"
  | "san_diego"
  | "sedona"
  | "south_miami"
  | "yellowstone";

/**
 * Type representing all workflows
 */
export type WorkflowCodenames =
  | "academic_resources"
  | "biographies"
  | "default"
  | "koa_marketing"
  | "patient_resources"
  | "untitled_workflow";

/**
 * Type representing all taxonomies
 */
export type TaxonomyCodenames =
  | "amenities"
  | "article_type"
  | "australian_museum_topics"
  | "camper_types"
  | "camping_topics"
  | "channel"
  | "event_topic"
  | "event_type"
  | "general_healthcare_topics"
  | "medical_specialties"
  | "music_articles"
  | "personas"
  | "ways_to_stay";

/**
 * Type representing all worksflow steps across all workflows
 */
export type WorkflowStepCodenames =
  | "admin_review"
  | "archived"
  | "copy_review"
  | "draft_5094e00"
  | "draft_97d445e"
  | "draft_a8b162c"
  | "draft_b242d4d"
  | "draft_d7852bc"
  | "draft"
  | "human_review"
  | "legal_review"
  | "marketing_review"
  | "medical_review"
  | "peer_review"
  | "published"
  | "reviewed_1778942"
  | "reviewed"
  | "scheduled"
  | "seo_generation_1e32614"
  | "seo_generation"
  | "staff_member_review";

/**
 * Type representing all element codenames across all content types
 */
export type ElementCodenames =
  | "address"
  | "amenities"
  | "api_preview"
  | "australian_museum_topics"
  | "author"
  | "autoplay"
  | "banner_body"
  | "banner_header"
  | "banner_image"
  | "biography"
  | "body_copy"
  | "body"
  | "book_now_cta_background_image"
  | "book_now_cta_background_video_link"
  | "book_now_cta_text"
  | "button_label"
  | "button_link"
  | "bynder_asset"
  | "camper_types"
  | "caption"
  | "channel"
  | "cloudinary_integration"
  | "content"
  | "cta_a"
  | "cta_b"
  | "description"
  | "email_address"
  | "email"
  | "end_date"
  | "event_topic"
  | "event_type"
  | "featured_content"
  | "first_name"
  | "form"
  | "google_place_id"
  | "guidelines"
  | "headline"
  | "hero_image"
  | "image_position"
  | "image"
  | "introduction"
  | "job_title"
  | "last_name"
  | "latitude_coordinate"
  | "linkedin"
  | "longitude_coordinate"
  | "medical_specialties"
  | "menu"
  | "metadata__description"
  | "metadata__keywords"
  | "metadata__title"
  | "metadata"
  | "music_topics"
  | "name"
  | "persona"
  | "personas"
  | "phone_number"
  | "phone"
  | "pim_integration_e_g__shopify"
  | "prefix"
  | "publish_date"
  | "related_articles"
  | "start_date"
  | "style"
  | "subheadline"
  | "subpages"
  | "suffixes"
  | "summary"
  | "team"
  | "title"
  | "type"
  | "url_slug"
  | "url"
  | "video_link"
  | "ways_to_stay"
  | "website"
  | "x"
  | "yelp_business_id";
