
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 🏕️KoA Personalization
* Environment: Production
* Id: f189fcee-05bc-0069-1f34-a1d35d692446
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for Amenities
 *
 * Codename: amenities
 * Id: 0c5ab2b4-b181-4565-9e74-a46f405ee702
 */
export const amenitiesValues = [
  "wifi",
  "swimming_pool",
  "playground",
  "camp_store",
  "laundry_facilities",
  "showers",
  "restrooms",
  "fire_pits",
  "picnic_tables",
  "pet_friendly",
  "fishing",
  "hiking_trails",
  "boat_launch",
  "full_hookup_sites",
  "electric_hookup",
  "water_hookup",
  "dump_station",
] as const;

/**
 * Type representing Amenities taxonomy
 *
 * Codename: amenities
 * Id: 0c5ab2b4-b181-4565-9e74-a46f405ee702
 */
export type Amenities = (typeof amenitiesValues)[number];

/**
 * Type guard for Amenities
 *
 * Codename: amenities
 * Id: 0c5ab2b4-b181-4565-9e74-a46f405ee702
 */
export function isAmenities(value: string | undefined | null): value is Amenities {
  return typeof value === "string" && (amenitiesValues as readonly string[]).includes(value);
}
