
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 🏕️KoA Personalization
* Environment: Production
* Id: f189fcee-05bc-0069-1f34-a1d35d692446
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for Article Type
 *
 * Codename: article_type
 * Id: 06a6efd4-18bb-4cfd-973b-cf581fb88f87
 */
export const articleTypeValues = [
  "clinical_guidelines",
  "case_study",
  "research",
  "healthcare_policy_update",
  "industry_updates",
  "patient_education",
  "educational",
  "institutional_announcement",
  "learning_materials",
  "professional_training",
  "music_article",
] as const;

/**
 * Type representing Article Type taxonomy
 *
 * Codename: article_type
 * Id: 06a6efd4-18bb-4cfd-973b-cf581fb88f87
 */
export type ArticleType = (typeof articleTypeValues)[number];

/**
 * Type guard for Article Type
 *
 * Codename: article_type
 * Id: 06a6efd4-18bb-4cfd-973b-cf581fb88f87
 */
export function isArticleType(value: string | undefined | null): value is ArticleType {
  return typeof value === "string" && (articleTypeValues as readonly string[]).includes(value);
}
