
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 🏕️KoA Personalization
* Environment: Production
* Id: f189fcee-05bc-0069-1f34-a1d35d692446
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for Australian Museum Topics
 *
 * Codename: australian_museum_topics
 * Id: 7d8568d8-8b86-4c91-b212-273febca0b2c
 */
export const australianMuseumTopicsValues = [
  "archaeology",
  "arachnology",
  "entomology",
  "herpetology",
  "ichthyology",
  "malacology",
  "mammalogy",
  "marine_invertebrates",
  "mineralogy",
  "ornithology",
  "palaeontology",
  "natural_sciences",
  "genomics",
  "wildlife_conservation",
  "sustainability",
  "human_evolution",
  "zoonotic_diseases",
  "earth_science",
  "life_sciences",
  "geo_sciences",
  "research_areas",
  "first_nations",
  "pasifika",
  "world_cultures",
  "pacific_collection",
  "cultural_collections",
  "cultural_studies",
  "school_programs",
  "vacation_care_programs",
  "tertiary_education",
  "early_years_education",
  "adult_community_programs",
  "workshops",
  "virtual_tours",
  "educational_programs",
  "animal_factsheets",
  "extinct_animals",
  "fossil_studies",
  "mineral_studies",
  "australia_over_time",
  "citizen_science",
  "fieldwork_expeditions",
  "touring_exhibitions",
  "museum_collections",
  "specialized_topics",
  "amri",
  "climate_solutions_centre",
  "lizard_island_research",
  "wildlife_genomics_centre",
  "research_institutes",
] as const;

/**
 * Type representing Australian Museum Topics taxonomy
 *
 * Codename: australian_museum_topics
 * Id: 7d8568d8-8b86-4c91-b212-273febca0b2c
 */
export type AustralianMuseumTopics = (typeof australianMuseumTopicsValues)[number];

/**
 * Type guard for Australian Museum Topics
 *
 * Codename: australian_museum_topics
 * Id: 7d8568d8-8b86-4c91-b212-273febca0b2c
 */
export function isAustralianMuseumTopics(value: string | undefined | null): value is AustralianMuseumTopics {
  return typeof value === "string" && (australianMuseumTopicsValues as readonly string[]).includes(value);
}
