
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 🏕️KoA Personalization
* Environment: Production
* Id: f189fcee-05bc-0069-1f34-a1d35d692446
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for Camping Topics
 *
 * Codename: camping_topics
 * Id: d6ba2c0f-e0c4-4e91-a148-44aceb6534b7
 */
export const campingTopicsValues = [
  "hiking",
  "fishing",
  "swimming",
  "boating",
  "wildlife_watching",
  "activities",
  "rv_sites",
  "tent_camping",
  "cabins",
  "group_areas",
  "site_types",
  "spring_camping",
  "summer_fun",
  "fall_colors",
  "winter_adventures",
  "seasons",
  "full_hookup",
  "electric_only",
  "primitive",
  "pet_friendly",
  "amenities",
  "first_time_campers",
  "family_camping",
  "safety_tips",
  "packing_lists",
  "tips_guides",
] as const;

/**
 * Type representing Camping Topics taxonomy
 *
 * Codename: camping_topics
 * Id: d6ba2c0f-e0c4-4e91-a148-44aceb6534b7
 */
export type CampingTopics = (typeof campingTopicsValues)[number];

/**
 * Type guard for Camping Topics
 *
 * Codename: camping_topics
 * Id: d6ba2c0f-e0c4-4e91-a148-44aceb6534b7
 */
export function isCampingTopics(value: string | undefined | null): value is CampingTopics {
  return typeof value === "string" && (campingTopicsValues as readonly string[]).includes(value);
}
