
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 🏕️KoA Personalization
* Environment: Production
* Id: f189fcee-05bc-0069-1f34-a1d35d692446
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for Channel
 *
 * Codename: channel
 * Id: b24fd662-b993-40bb-9c07-47c1de622e21
 */
export const channelValues = [
  "website_a",
  "website_b",
  "website_s_",
  "x",
  "linkedin",
  "social_media",
  "intranet",
] as const;

/**
 * Type representing Channel taxonomy
 *
 * Codename: channel
 * Id: b24fd662-b993-40bb-9c07-47c1de622e21
 */
export type Channel = (typeof channelValues)[number];

/**
 * Type guard for Channel
 *
 * Codename: channel
 * Id: b24fd662-b993-40bb-9c07-47c1de622e21
 */
export function isChannel(value: string | undefined | null): value is Channel {
  return typeof value === "string" && (channelValues as readonly string[]).includes(value);
}
