
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 🏕️KoA Personalization
* Environment: Production
* Id: f189fcee-05bc-0069-1f34-a1d35d692446
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for Event Type
 *
 * Codename: event_type
 * Id: 54519543-3e87-541d-a060-1246d721db5e
 */
export const eventTypeValues = ["seminar", "webinar", "workshop"] as const;

/**
 * Type representing Event Type taxonomy
 *
 * Codename: event_type
 * Id: 54519543-3e87-541d-a060-1246d721db5e
 */
export type EventType = (typeof eventTypeValues)[number];

/**
 * Type guard for Event Type
 *
 * Codename: event_type
 * Id: 54519543-3e87-541d-a060-1246d721db5e
 */
export function isEventType(value: string | undefined | null): value is EventType {
  return typeof value === "string" && (eventTypeValues as readonly string[]).includes(value);
}
