
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 🏕️KoA Personalization
* Environment: Production
* Id: f189fcee-05bc-0069-1f34-a1d35d692446
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for Music Articles
 *
 * Codename: music_articles
 * Id: 5529c435-dcf2-4535-82d7-589c1a853f4d
 */
export const musicArticlesValues = [
  "folk",
  "instrumental",
  "metal",
  "emo",
  "funk",
  "disco",
  "electronic",
  "country",
  "jazz",
  "hip_hop_rap",
  "pop",
  "post_rock",
  "pop_punk",
  "punk",
  "hardcore",
  "rock",
] as const;

/**
 * Type representing Music Articles taxonomy
 *
 * Codename: music_articles
 * Id: 5529c435-dcf2-4535-82d7-589c1a853f4d
 */
export type MusicArticles = (typeof musicArticlesValues)[number];

/**
 * Type guard for Music Articles
 *
 * Codename: music_articles
 * Id: 5529c435-dcf2-4535-82d7-589c1a853f4d
 */
export function isMusicArticles(value: string | undefined | null): value is MusicArticles {
  return typeof value === "string" && (musicArticlesValues as readonly string[]).includes(value);
}
