
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 🏕️KoA Personalization
* Environment: Production
* Id: f189fcee-05bc-0069-1f34-a1d35d692446
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for Personas
 *
 * Codename: personas
 * Id: 927a64c0-3b11-4128-a2cc-10fc5d613574
 */
export const personasValues = ["regular_vistor", "new_vistitor"] as const;

/**
 * Type representing Personas taxonomy
 *
 * Codename: personas
 * Id: 927a64c0-3b11-4128-a2cc-10fc5d613574
 */
export type Personas = (typeof personasValues)[number];

/**
 * Type guard for Personas
 *
 * Codename: personas
 * Id: 927a64c0-3b11-4128-a2cc-10fc5d613574
 */
export function isPersonas(value: string | undefined | null): value is Personas {
  return typeof value === "string" && (personasValues as readonly string[]).includes(value);
}
