
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 🏕️KoA Personalization
* Environment: Production
* Id: f189fcee-05bc-0069-1f34-a1d35d692446
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for Region
 *
 * Codename: region
 * Id: bf36a90c-d537-46b1-999b-ee91c3ea5763
 */
export const regionValues = ["midwest", "southwest", "east_coast", "west_coast", "northwest", "southeast"] as const;

/**
 * Type representing Region taxonomy
 *
 * Codename: region
 * Id: bf36a90c-d537-46b1-999b-ee91c3ea5763
 */
export type Region = (typeof regionValues)[number];

/**
 * Type guard for Region
 *
 * Codename: region
 * Id: bf36a90c-d537-46b1-999b-ee91c3ea5763
 */
export function isRegion(value: string | undefined | null): value is Region {
  return typeof value === "string" && (regionValues as readonly string[]).includes(value);
}
