
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 🏕️KoA Personalization
* Environment: Production
* Id: f189fcee-05bc-0069-1f34-a1d35d692446
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for Ways to Stay
 *
 * Codename: ways_to_stay
 * Id: ab5edf8f-167d-4df8-8193-59566cf1816d
 */
export const waysToStayValues = [
  "rv_sites",
  "tent_camping",
  "cabins",
  "glamping",
  "group_sites",
  "primitive_camping",
  "yurts",
  "tiny_homes",
] as const;

/**
 * Type representing Ways to Stay taxonomy
 *
 * Codename: ways_to_stay
 * Id: ab5edf8f-167d-4df8-8193-59566cf1816d
 */
export type WaysToStay = (typeof waysToStayValues)[number];

/**
 * Type guard for Ways to Stay
 *
 * Codename: ways_to_stay
 * Id: ab5edf8f-167d-4df8-8193-59566cf1816d
 */
export function isWaysToStay(value: string | undefined | null): value is WaysToStay {
  return typeof value === "string" && (waysToStayValues as readonly string[]).includes(value);
}
