
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 🏕️KoA Personalization
* Environment: Production
* Id: f189fcee-05bc-0069-1f34-a1d35d692446
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { Channel, CampingTopics } from "../taxonomies/index.ts";
import type { CoreContentType } from "../system/index.ts";
import type { Metadata } from "../content-type-snippets/index.ts";
import type { Person } from "./index.ts";

/**
 * Article
 *
 * Id: d622fc28-5202-511a-9dbf-a3ee363b6c7c
 * Codename: article
 */
export type Article = CoreContentType<
  ArticleElementCodenames,
  {
    /**
     * Title
     *
     * Type: text
     * Required: true
     * Codename: title
     * Id: ad06c69a-9ccd-5d8c-b2de-b6a9f83d00fc
     */
    readonly title: Elements.TextElement;
    /**
     * Publish Date
     *
     * Type: date_time
     * Required: true
     * Codename: publish_date
     * Id: abdf08ea-55f0-5460-96e0-391f7471c7e9
     */
    readonly publish_date: Elements.DateTimeElement;
    /**
     * Introduction
     *
     * Type: text
     * Required: true
     * Codename: introduction
     * Id: c3fc1a88-5577-5130-b0aa-b1837c009ba6
     */
    readonly introduction: Elements.TextElement;
    /**
     * Author
     *
     * Type: modular_content
     * Required: false
     * Codename: author
     * Id: 645445ef-c1a0-4eec-bbec-fcb2ce2e1862
     */
    readonly author: Elements.LinkedItemsElement<Person>;
    /**
     * Image
     *
     * Type: asset
     * Required: true
     * Codename: image
     * Id: 8c501358-d0f7-5959-95bd-2991f1215e33
     */
    readonly image: Elements.AssetsElement;
    /**
     * Body Copy
     *
     * Type: rich_text
     * Required: true
     * Codename: body_copy
     * Id: 0747fb13-7383-59fe-bf64-2bab6d384279
     */
    readonly body_copy: Elements.RichTextElement<CoreContentType>;
    /**
     * Related Articles
     *
     * Type: modular_content
     * Required: false
     * Codename: related_articles
     * Id: bf44c9a2-6bd9-455a-8cfd-68cc806cf359
     */
    readonly related_articles: Elements.LinkedItemsElement<Article>;
    /**
     * URL slug
     *
     * Type: url_slug
     * Required: true
     * Codename: url_slug
     * Id: 33f5f8e9-aca2-4f52-a3b2-68ea6337ed59
     */
    readonly url_slug: Elements.UrlSlugElement;
    /**
     * Channel
     *
     * Type: taxonomy
     * Required: false
     * Codename: channel
     * Id: 59bea66f-22fa-458d-a842-a482d9e764f6
     */
    readonly channel: Elements.TaxonomyElement<Channel, "channel">;
    /**
     * X
     *
     * Type: text
     * Required: false
     * Codename: x
     * Id: 00a53b1d-53cc-4bc3-babd-2e47e4158d11
     */
    readonly x: Elements.TextElement;
    /**
     * LinkedIn
     *
     * Type: text
     * Required: false
     * Codename: linkedin
     * Id: 8cbf0a1a-9dd8-44b5-82d0-bffc64d61151
     */
    readonly linkedin: Elements.TextElement;
    /**
     * Camping Topics
     *
     * Type: taxonomy
     * Required: false
     * Codename: music_topics
     * Id: f939d795-a222-4c6f-9e46-98d45cd96563
     * Guidelines: Select relevant camping topics, activities, and site types for this article
     */
    readonly music_topics: Elements.TaxonomyElement<CampingTopics, "music_topics">;
  } & Metadata,
  "article"
>;

/**
 * Type representing all available element codenames for Article
 */
export type ArticleElementCodenames =
  | "title"
  | "publish_date"
  | "introduction"
  | "author"
  | "image"
  | "body_copy"
  | "related_articles"
  | "metadata__title"
  | "metadata__keywords"
  | "metadata__description"
  | "url_slug"
  | "channel"
  | "x"
  | "linkedin"
  | "music_topics";

/**
 * Type guard for Article
 *
 * Id: d622fc28-5202-511a-9dbf-a3ee363b6c7c
 * Codename: article
 */
export function isArticle(item: CoreContentType | undefined | null): item is Article {
  return item?.system?.type === "article";
}
