
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 🏕️KoA Personalization
* Environment: Production
* Id: f189fcee-05bc-0069-1f34-a1d35d692446
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * Bynder Image
 *
 * Id: 6f13003a-f937-4e11-9c60-17b8019f9601
 * Codename: bynder_image
 */
export type BynderImage = CoreContentType<
  BynderImageElementCodenames,
  {
    /**
     * Title
     *
     * Type: text
     * Required: true
     * Codename: title
     * Id: 5b685670-8fb4-42e1-8b84-18bede32cbbf
     */
    readonly title: Elements.TextElement;
    /**
     * Bynder Asset Selector
     *
     * Type: custom
     * Required: false
     * Codename: bynder_asset
     * Id: 009dafac-eae9-4a14-8ef1-755f8899276a
     */
    readonly bynder_asset: Elements.CustomElement;
  },
  "bynder_image"
>;

/**
 * Type representing all available element codenames for Bynder Image
 */
export type BynderImageElementCodenames = "title" | "bynder_asset";

/**
 * Type guard for Bynder Image
 *
 * Id: 6f13003a-f937-4e11-9c60-17b8019f9601
 * Codename: bynder_image
 */
export function isBynderImage(item: CoreContentType | undefined | null): item is BynderImage {
  return item?.system?.type === "bynder_image";
}
