
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 🏕️KoA Personalization
* Environment: Production
* Id: f189fcee-05bc-0069-1f34-a1d35d692446
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { Amenities, WaysToStay } from "../taxonomies/index.ts";
import type { CoreContentType } from "../system/index.ts";
import type { Metadata } from "../content-type-snippets/index.ts";
import type { Page } from "./index.ts";

/**
 * Campground
 *
 * Id: c10b39e4-5c52-49c7-ad97-2bbcc51c52bc
 * Codename: campground
 */
export type Campground = CoreContentType<
  CampgroundElementCodenames,
  {
    /**
     * Name
     *
     * Type: text
     * Required: true
     * Codename: name
     * Id: afe458ff-27c9-4e18-9825-deb846949c90
     */
    readonly name: Elements.TextElement;
    /**
     * Phone Number
     *
     * Type: text
     * Required: true
     * Codename: phone_number
     * Id: 324aa81e-b3bd-430a-bb2f-aae18a3af1b8
     * Guidelines: Please include the international code and area code (ex. 1-555-555-5555)
     */
    readonly phone_number: Elements.TextElement;
    /**
     * Email Address
     *
     * Type: text
     * Required: true
     * Codename: email_address
     * Id: fecb9889-21df-4ee8-9c5b-ad30aa7b2929
     */
    readonly email_address: Elements.TextElement;
    /**
     * Address
     *
     * Type: text
     * Required: false
     * Codename: address
     * Id: 2016528d-b381-4707-be65-0a87e521fdc2
     */
    readonly address: Elements.TextElement;
    /**
     * Amenities
     *
     * Type: taxonomy
     * Required: true
     * Codename: amenities
     * Id: 86d1cbe9-9c7e-4838-b28f-b61003150f4c
     */
    readonly amenities: Elements.TaxonomyElement<Amenities, "amenities">;
    /**
     * Ways to Stay
     *
     * Type: taxonomy
     * Required: false
     * Codename: ways_to_stay
     * Id: 674f63fe-78c7-4214-8158-01382fee12fb
     */
    readonly ways_to_stay: Elements.TaxonomyElement<WaysToStay, "ways_to_stay">;
    /**
     * Menu
     *
     * Type: subpages
     * Required: false
     * Codename: menu
     * Id: a2be71d5-06b5-4817-9ca3-cb54f3e2953f
     */
    readonly menu: Elements.LinkedItemsElement<Page>;
    /**
     * Book Now CTA Text
     *
     * Type: text
     * Required: false
     * Codename: book_now_cta_text
     * Id: faedee24-c219-4b60-bda8-9967eb315cb8
     */
    readonly book_now_cta_text: Elements.TextElement;
    /**
     * Book Now CTA Background Image
     *
     * Type: asset
     * Required: false
     * Codename: book_now_cta_background_image
     * Id: 76c82cd2-a375-4f78-9a1b-0297fea4efeb
     */
    readonly book_now_cta_background_image: Elements.AssetsElement;
    /**
     * Book Now CTA Background Video Link
     *
     * Type: text
     * Required: false
     * Codename: book_now_cta_background_video_link
     * Id: ed09bf9f-cde4-4973-8d3f-4d3060b98822
     * Guidelines: If you want to use a background video, put in the Vimeo link.
     */
    readonly book_now_cta_background_video_link: Elements.TextElement;
    /**
     * Banner Header
     *
     * Type: text
     * Required: true
     * Codename: banner_header
     * Id: cc1682c8-b337-461f-b254-8e01591182a8
     */
    readonly banner_header: Elements.TextElement;
    /**
     * Banner Body
     *
     * Type: rich_text
     * Required: true
     * Codename: banner_body
     * Id: d6c1c62b-5815-4db6-80e1-4362c1a59929
     * Guidelines: Tell us about your campground. Include information on ways to stay, recreation opportunities, attractions, etc.
     */
    readonly banner_body: Elements.RichTextElement<CoreContentType>;
    /**
     * Banner Image
     *
     * Type: asset
     * Required: false
     * Codename: banner_image
     * Id: 27a0eef2-62b2-437c-b076-7cb194c2dad1
     */
    readonly banner_image: Elements.AssetsElement;
    /**
     * URL
     *
     * Type: url_slug
     * Required: false
     * Codename: url
     * Id: ce448b05-531f-4d83-a8a3-8517a5430b2d
     */
    readonly url: Elements.UrlSlugElement;
  } & Metadata,
  "campground"
>;

/**
 * Type representing all available element codenames for Campground
 */
export type CampgroundElementCodenames =
  | "name"
  | "phone_number"
  | "email_address"
  | "address"
  | "amenities"
  | "ways_to_stay"
  | "menu"
  | "book_now_cta_text"
  | "book_now_cta_background_image"
  | "book_now_cta_background_video_link"
  | "banner_header"
  | "banner_body"
  | "banner_image"
  | "metadata__title"
  | "metadata__keywords"
  | "metadata__description"
  | "url";

/**
 * Type guard for Campground
 *
 * Id: c10b39e4-5c52-49c7-ad97-2bbcc51c52bc
 * Codename: campground
 */
export function isCampground(item: CoreContentType | undefined | null): item is Campground {
  return item?.system?.type === "campground";
}
