
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 🏕️KoA Personalization
* Environment: Production
* Id: f189fcee-05bc-0069-1f34-a1d35d692446
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * Form (Hubspot integration)
 *
 * Id: 13f798f5-3fb9-4085-afdf-247caf8f95a7
 * Codename: form__hubspot_integration
 */
export type FormHubspotIntegration = CoreContentType<
  FormHubspotIntegrationElementCodenames,
  {
    /**
     * Form
     *
     * Type: custom
     * Required: false
     * Codename: form
     * Id: 80a30613-4def-437b-bcab-c009f349d906
     */
    readonly form: Elements.CustomElement;
  },
  "form__hubspot_integration"
>;

/**
 * Type representing all available element codenames for Form (Hubspot integration)
 */
export type FormHubspotIntegrationElementCodenames = "form";

/**
 * Type guard for Form (Hubspot integration)
 *
 * Id: 13f798f5-3fb9-4085-afdf-247caf8f95a7
 * Codename: form__hubspot_integration
 */
export function isFormHubspotIntegration(item: CoreContentType | undefined | null): item is FormHubspotIntegration {
  return item?.system?.type === "form__hubspot_integration";
}
