
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: 🏕️KoA Personalization
* Environment: Production
* Id: f189fcee-05bc-0069-1f34-a1d35d692446
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { AustralianMuseumTopics } from "../taxonomies/index.ts";
import type { CoreContentType } from "../system/index.ts";

/**
 * Product
 *
 * Id: 25abb5c4-00d7-4ddc-8e09-181d283c1407
 * Codename: product
 */
export type Product = CoreContentType<
  ProductElementCodenames,
  {
    /**
     * Name
     *
     * Type: text
     * Required: false
     * Codename: name
     * Id: cb96368f-900c-40d0-bb0c-2975009b4ea4
     */
    readonly name: Elements.TextElement;
    /**
     * Body
     *
     * Type: rich_text
     * Required: false
     * Codename: body
     * Id: c6356ff5-bc7e-46aa-8d46-04ab10b8afad
     */
    readonly body: Elements.RichTextElement<CoreContentType>;
    /**
     * Australian Museum Topics
     *
     * Type: taxonomy
     * Required: false
     * Codename: australian_museum_topics
     * Id: e3890835-d275-4f9e-82db-43b20672906a
     */
    readonly australian_museum_topics: Elements.TaxonomyElement<AustralianMuseumTopics, "australian_museum_topics">;
    /**
     * PIM integration e.g. Shopify
     *
     * Type: custom
     * Required: false
     * Codename: pim_integration_e_g__shopify
     * Id: c13add00-8fca-446a-884d-68cf2207b2ac
     */
    readonly pim_integration_e_g__shopify: Elements.CustomElement;
    /**
     * Cloudinary integration
     *
     * Type: custom
     * Required: false
     * Codename: cloudinary_integration
     * Id: 1029f1e2-5fcc-4466-9af0-5ee43736eff8
     */
    readonly cloudinary_integration: Elements.CustomElement;
  },
  "product"
>;

/**
 * Type representing all available element codenames for Product
 */
export type ProductElementCodenames =
  | "name"
  | "body"
  | "australian_museum_topics"
  | "pim_integration_e_g__shopify"
  | "cloudinary_integration";

/**
 * Type guard for Product
 *
 * Id: 25abb5c4-00d7-4ddc-8e09-181d283c1407
 * Codename: product
 */
export function isProduct(item: CoreContentType | undefined | null): item is Product {
  return item?.system?.type === "product";
}
